### ISSUE TITLE
DNS and VIP should be configurable 

### ISSUE THREAD

**Issue by flyemsafe** [tosin2013/openstack-all-in-one#2]
The `./openstack-all-in-one/create-source.sh networkinterface` should allow you to specify a VIP and DNS_SERVER1.

**Comment by tosin2013** [comment]
You are correct i will make that change.

**Comment by tosin2013** [comment]
This has been fixed in the following commit 
https://github.com/tosin2013/openstack-all-in-one/commit/95f7d6a4c9d0865fcc79f8f6191887e3178d3ae0
